#!/bin/bash
cd "${0%/*}" || exit
. "${WM_PROJECT_DIR:?}"/bin/tools/RunFunctions
#------------------------------------------------------------------------------

# dummy file for post-processing with paraview
touch post.foam

# mesh 0
# cp system/blockMeshDict.m0 system/blockMeshDict
# sed -i "s/^deltaT.*/deltaT          2.0e-5;/" system/controlDict

# mesh 1
cp system/blockMeshDict.m1 system/blockMeshDict
sed -i "s/^deltaT.*/deltaT          1.0e-5;/" system/controlDict

# mesh creation
runApplication blockMesh

# parallel run
cp -r 0.org 0
runApplication decomposePar
runParallel renumberMesh -overwrite
runParallel checkMesh -allGeometry -allTopology

# execute flow solver
runParallel potentialFoam -writephi
runParallel $(getApplication)
runParallel postProcess -func "writeCellCentres" -constant -time none
mv log.postProcess log.postProcess.writeCellCentres
runParallel postProcess -func "writeCellVolumes" -constant -time none
mv log.postProcess log.postProcess.writeCellVolumes

# cleaning up
find ./ -type f \( -name "phi" -o -name "phi_0" -o -name "U_0" -o -name "gradU" \) -exec rm {} \;

#------------------------------------------------------------------------------
